# Generated by Django 5.1.7 on 2025-03-30 17:14

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default/default_avatar.png', null=True, upload_to=users.models.profile_pic_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=15),
        ),
    ]
