# Generated by Django 5.1.7 on 2025-04-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
        ('users', '0002_profile_profile_picture_alter_profile_phone_number'),
    ]

    operations = [
    ]
